config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :show, :new, :create, :edit, :update]
  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do
    resources :order_items, only: [:new, :create]
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
  end
  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:show, :index, :create, :edit, :update]
    end
  end
end

app/models/product_model.rb
class ProductModel < ApplicationRecord
  validates :name, :weight, :width, :height, :depth, :sku, :supplier, presence: true
  validates :sku, length: { is: 20 }
  validates :sku, uniqueness: true
  validates :weight, :width, :height, :depth, numericality: { greater_than: 0 }
  belongs_to :supplier
  has_many :order_items
  has_many :orders, through: :order_items
end

app/controllers/product_models_controller.rb
class ProductModelsController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  before_action :set_product_model, only: [:show, :edit, :update]

  def index
    @product_models = ProductModel.all
  end

  def new
    @product_model = ProductModel.new
    @suppliers = Supplier.all
  end

  def create
    @product_model = ProductModel.new(product_model_params)
    if @product_model.save
      redirect_to @product_model, notice: 'Modelo de Produto cadastrado com sucesso.'
    else
      @suppliers = Supplier.all
      flash.now[:notice] = "Não foi possivel cadastrar o modelo de produto."
      render :new
    end
  end

  def show
  end

  def edit
    @suppliers = Supplier.all
  end

  def update
    if @product_model.update(product_model_params)
      redirect_to product_models_path
    else
      @suppliers = Supplier.all
      render :edit
    end
  end

  private

  def product_model_params
    params.require(:product_model).permit(:name, :weight, :width, :height, :depth, :sku, :supplier_id)
  end

  def set_product_model
    @product_model = ProductModel.find(params[:id])
  end

end

app/views/product_models/_form.html.erb
<%= form_with model: product_model do |f| %>

  <%= render "shared/form_errors", object: product_model %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :weight %>
    <%= f.number_field :weight %>
  </div>

  <div>
    <%= f.label :height %>
    <%= f.number_field :height %>
  </div>

  <div>
    <%= f.label :width %>
    <%= f.number_field :width %>
  </div>

  <div>
    <%= f.label :depth %>
    <%= f.number_field :depth %>
  </div>

  <div>
    <%= f.label :sku %>
    <%= f.text_field :sku %>
  </div>

  <div>
    <%= f.label :supplier_id %>
    <%= f.collection_select :supplier_id, suppliers, :id, :brand_name  %>
  </div>

  <div>
    <%= f.submit 'Enviar' %>
  </div>

<% end %>

app/views/product_models/edit.html.erb
<h1>Editar Modelo de Produto</h1>

<%= render partial: 'form', locals: { product_model: @product_model, suppliers: @suppliers } %>

app/views/product_models/index.html.erb
<h1>Modelos de Produtos</h1>

<%= link_to 'Cadastrar Novo', new_product_model_path %>
<% if @product_models.any? %>
  <table>
    <thead>
      <tr>
        <th>Nome</th>
        <th>SKU</th>
        <th>Fornecedor</th>
      </tr>
    </thead>
    <tbody>
      <% @product_models.each do |product_model| %>
        <tr>
          <td><%= product_model.name %></td>
          <td><%= product_model.sku %></td>
          <td><%= product_model.supplier.brand_name %></td>
          <td><%= button_to "Editar", edit_product_model_path(product_model), method: :get, id:"#{dom_id(product_model)}" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>Nenhum modelo de produto cadastrado.</p>
<% end %>

app/views/product_models/new.html.erb
<h1>Cadastrar Novo Modelo de Produto</h1>

<%= render partial: 'form', locals: { product_model: @product_model, suppliers: @suppliers } %>

app/views/product_models/show.html.erb
<h1><%= @product_model.name %></h1>
<dl>
  <dt>Fornecedor:</dt>
  <dd><%= @product_model.supplier.brand_name %></dd>
  <dt>SKU:</dt>
  <dd><%= @product_model.sku %></dd>
  <dt>Dimensão:</dt>
  <dd><%= @product_model.width %> x <%= @product_model.height %> x <%= @product_model.depth %> cm</dd>
  <dt>Peso:</dt>
  <dd><%= @product_model.weight %>g</dd>
</dl>