config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :show, :new, :create, :edit, :update]
  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do
    resources :order_items, only: [:new, :create]
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
  end
  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:show, :index, :create, :edit, :update]
    end
  end
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  validates :corporate_name, :brand_name, :registration_number, :email, presence: true
  validates :registration_number, uniqueness: true
  validates :registration_number, length: { is: 13 }

  has_many :product_models
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController

  before_action :set_supplier, only: [:show, :edit, :update]

  def index
    @suppliers = Supplier.all
  end

  def show
    @product_models = @supplier.product_models
  end

  def new
    @supplier = Supplier.new
  end

  def edit
  end

  def create
    @supplier = Supplier.new(supplier_params)
    if @supplier.save
      redirect_to @supplier, notice: "Fornecedor cadastrado com sucesso."
    else
      flash.now[:notice] = "Fornecedor não cadastrado."
      render :new
    end
  end

  def update
    if @supplier.update(supplier_params)
      redirect_to @supplier, notice: "Fornecedor atualizado com sucesso."
    else
      flash.now[:notice] = "Fornecedor não atualizado."
      render :edit
    end
  end

  private

  def set_supplier
    @supplier = Supplier.find(params[:id])
  end

  def supplier_params
    params.require(:supplier).permit(:corporate_name, :brand_name, :registration_number,
                                    :full_address, :city, :state, :email)
  end

end

app/views/suppliers/_form.html.erb
<%= form_with model: supplier do |f| %>

  <%= render "shared/form_errors", object: supplier %>

  <div>
    <%= f.label :corporate_name %>
    <%= f.text_field :corporate_name %>
  </div>

  <div>
    <%= f.label :brand_name %>
    <%= f.text_field :brand_name %>
  </div>

  <div>
    <%= f.label :registration_number %>
    <%= f.number_field :registration_number %>
  </div>

  <div>
    <%= f.label :full_address %>
    <%= f.text_field :full_address %>
  </div>

  <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div>
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.submit "Enviar" %>
  </div>

<% end %>

app/views/suppliers/edit.html.erb
<h1>Editar fornecedor</h1>

<%= render partial: 'form', locals: { supplier: @supplier } %>

app/views/suppliers/index.html.erb
<h1>Fornecedores</h1>

<% if @suppliers.any? %>
  <table>
    <thead>
      <tr>
        <th>Nome</th>
        <th>Localização</th>
      </tr>
    </thead>
    <tbody>
      <% @suppliers.each do |s| %>
        <tr>
          <td><%= link_to s.brand_name, s %></td>
          <td><%= s.city %> - <%= s.state %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>Nenhum fornecedor cadastrado.</p>
<% end %>

<%= link_to 'Cadastrar novo fornecedor', new_supplier_path %>

app/views/suppliers/new.html.erb
<h1>Novo fornecedor</h1>

<%= render partial: 'form', locals: { supplier: @supplier } %>

app/views/suppliers/show.html.erb
<h1>Fornecedor <%= @supplier.brand_name %></h1>
<h2><%= @supplier.corporate_name %></h2>

<dl>
  <dt>Documento:</dt>
  <dd><%= @supplier.registration_number %></dd>
  <dt>Endereço:</dt>
  <dd><%= @supplier.full_address %> - <%= @supplier.city %> - <%= @supplier.state %></dd>
  <dt>E-mail:</dt>
  <dd><%= @supplier.email %></dd>
</dl>

<%= link_to 'Editar', edit_supplier_path(@supplier) %>

<% if @product_models.any? %>
  <h3>Produtos Cadastrados</h3>
  <table>
    <tr>
      <th>Nome</th>
      <th>Dimensões</th>
      <th>Peso</th>
      <th>SKU</th>
    </tr>
    <% @product_models.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td><%= product.width %> x <%= product.height %> x <%= product.depth %> cm </td>
      <td><%= product.weight %>g</td>
      <td><%= product.sku %></td>
    </tr>
    <% end %>
  </table>
<% end %>

<div>
  <%= link_to 'Voltar', root_path %>
</div>